import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('../public/mathworld_v2/', import.meta.url).pathname;
const context=vm.createContext({structuredClone,Math,console});const modules=new Map();
async function module(path){path=path.split('?')[0];if(modules.has(path))return modules.get(path);const m=new vm.SourceTextModule(await fs.readFile(path,'utf8'),{context,identifier:path});modules.set(path,m);await m.link((spec,owner)=>module(new URL(spec,'file://'+owner.identifier).pathname));return m;}
const m=await module(root+'model.js');await m.evaluate();const M=m.namespace;let checks=0;
function test(name,f){f();checks++;console.log('PASS',name);}
const plain=b=>JSON.parse(JSON.stringify(b));
test('nested arithmetic wounds restore in reverse order with exact fractions',()=>{const b=M.makeBody();M.damage(b,{op:'add',value:3},'A');M.damage(b,{op:'mul',value:2},'B');M.damage(b,{op:'div',value:3},'C');assert.equal(M.textF(b.p[0]),'16/3');assert.equal(b.scars.length,3);assert(M.selfOperation(b,'mul',3).repaired);assert.equal(M.textF(b.p[0]),'16');assert(M.selfOperation(b,'div',2).repaired);assert(M.selfOperation(b,'sub',3).repaired);assert.equal(b.form,'5');assert.equal(b.scars.length,0);});
test('an incorrect self operation really changes the body, and can be undone',()=>{const b=M.makeBody();M.damage(b,{op:'mul',value:2});assert(!M.selfOperation(b,'sub',2).repaired);assert.equal(M.textF(b.p[0]),'8');assert(M.selfOperation(b,'add',2).repaired);assert.equal(M.textF(b.p[0]),'10');assert(M.selfOperation(b,'div',2).repaired);assert.equal(b.form,'5');});
test('500 deterministic arithmetic corruption/repair round trips',()=>{for(let i=0;i<500;i++){const b=M.makeBody();const ops=['add','sub','mul','div'];for(let j=0;j<8;j++)M.damage(b,{op:ops[(i+j)%4],value:1+(i*j+3)%9},'Property');while(b.scars.length){const h=M.repairHint(b);assert(M.selfOperation(b,h.op,h.value,h.term).repaired);}assert.equal(b.form,'5');assert.equal(M.textF(b.p[0]),'5');assert(!b.dead);}});
test('x + 5 = 0 solves to -5, not an undefined variable',()=>{const b=M.makeBody();M.damage(b,{op:'add',value:1,term:'x'});M.damage(b,{op:'seal'});assert(!b.dead);assert(M.selfOperation(b,'balance').repaired);assert.equal(b.form,'x ∈ {−5}'.replace('−','-'));});
test('quadratic roots preserve both -4 and -1',()=>{const b=M.makeBody();M.damage(b,{op:'forge'});assert.equal(b.form,'x² + 5x + 4');M.damage(b,{op:'seal'});assert.equal(M.textF(M.discriminant(b.p)),'9');assert.equal(M.roots(b.p),'{-4, -1}');M.selfOperation(b,'balance');assert.equal(b.form,'x ∈ {-4, -1}');assert(!b.dead);});
test('negative discriminant is lethal only when an equation is constrained',()=>{const b=M.makeBody();M.damage(b,{op:'forge'});M.damage(b,{op:'add',value:4});assert(!b.dead);M.damage(b,{op:'seal'});assert(b.dead);assert(b.reason.includes('−')||b.reason.includes('-7'));});
test('irrational real roots are not lethal and use denominator 2a',()=>{const b=M.makeBody();b.p=[M.F(-2),M.F(0),M.F(1)];b.form='x² − 2';M.damage(b,{op:'seal'});assert(!b.dead);assert.equal(M.textF(M.discriminant(b.p)),'8');assert.equal(M.roots(b.p),'{(−(0) ± √(8)) / (2)}');});
test('zero division is immediately undefined',()=>{const b=M.makeBody();M.damage(b,{op:'div',value:0});assert(b.dead);assert.equal(b.form,'(5) / 0');});
test('derivative repair retains the initial-value anchor; integral retains C',()=>{const b=M.makeBody();M.damage(b,{op:'div',value:2});M.damage(b,{op:'der'},'D');assert.equal(b.form,'0');assert(M.repairHint(b).label.includes('5/2'));assert(M.selfOperation(b,'int').repaired);assert.equal(M.textF(b.p[0]),'5/2');M.damage(b,{op:'int'},'I');assert.equal(b.form,'(5/2)x + C');assert(b.freeC);M.selfOperation(b,'der');assert.equal(M.textF(b.p[0]),'5/2');assert(!b.freeC);});
test('a zero leading quadratic coefficient is treated as linear',()=>{assert.equal(M.roots([M.F(4),M.F(2),M.F(0)]),'{-2}');});
test('defeat retry restores encounter entrance, not pristine body',()=>{const g=M.makeGame();M.damage(g.body,{op:'add',value:3},'Old scar');M.startEncounter(g);M.damage(g.body,{op:'div',value:0});g.status='lost';M.retry(g);assert.equal(g.body.form,'(5) + 3');assert.equal(g.body.scars.length,1);assert(!g.body.dead);});
test('shield absorbs zero division and perfect defense gains focus',()=>{const g=M.makeGame();M.startEncounter(g);g.enemies[0].intent={op:'div',value:0};assert(M.guard(g));assert.equal(M.receive(g,0,'miss'),'ward');assert(!g.body.dead);g.enemies[0].intent={op:'add',value:3};assert.equal(M.receive(g,0,'perfect'),'blocked');assert(g.enemies[0].skip);assert.equal(g.focus,2);});
test('missed timing still applies correct mathematics, successful timing interrupts',()=>{const g=M.makeGame();M.startEncounter(g);const e=g.enemies[0];M.attack(g,e.id,'sub',3,'','miss');assert(e.resolved);const h=M.makeGame();h.chapter=1;M.startEncounter(h);const two=h.enemies[0];M.attack(h,two.id,'div',2,'','good');assert(two.cancelled);assert(!two.resolved);});
test('ordered cooperative forecast catches degree + seal + constant kill',()=>{const g=M.makeGame();g.chapter=3;M.startEncounter(g);g.enemies[0].intent={op:'forge'};g.enemies[1].intent={op:'seal'};g.enemies[2].intent={op:'add',value:4};const f=M.forecast(g);assert(!f[0].dead);assert(!f[1].dead);assert(f[2].dead);assert.equal(M.textF(M.discriminant(g.body.p)),'0');});
test('every encounter is solvable with visible hints and good timed actions',()=>{const g=M.makeGame(42);for(let chapter=0;chapter<M.STAGES.length;chapter++){assert.equal(g.chapter,chapter);M.startEncounter(g);let turns=0;while(g.status==='player'){while(g.ap&&g.status==='player'){const e=g.enemies.find(e=>!e.resolved),h=M.enemyHint(e);assert(h,`${e.name} missing hint`);const r=M.attack(g,e.id,h.op,h.value||1,'','good');assert(r.ok,`${e.name}: ${r.note}`);}if(g.status==='clear'||g.status==='victory')break;for(const e of g.enemies)M.receive(g,e.id,'good');M.nextTurn(g);assert(++turns<20);}assert(['clear','victory'].includes(g.status));if(g.status==='clear')M.nextEncounter(g);}assert.equal(g.status,'victory');assert.equal(g.enemies[0].form,'y = 3 + Ce⁻²ˣ');assert.equal(g.body.form,'5');});
test('persistent body crosses encounter boundary without healing',()=>{const g=M.makeGame();M.startEncounter(g);M.damage(g.body,{op:'add',value:3},'First');for(const e of g.enemies){const h=M.enemyHint(e);M.attack(g,e.id,h.op,h.value,'','good');}assert.equal(g.status,'clear');M.nextEncounter(g);M.startEncounter(g);assert.equal(g.body.form,'(5) + 3');assert.equal(g.body.scars.length,1);});
console.log(`${checks} suites passed; 500 randomized-body round trips; all six encounters completed.`);
