/**
 * Types for the 2026 YKS medicine preference dataset.
 *
 * Everything here is generated by `scripts/yks/extract-report.mjs` from the
 * research report markdown. Do not hand-edit the JSON files: re-run the
 * extractor instead, so the repair table stays the single documented account of
 * how the source was cleaned.
 */

/** Coarse band used for filtering and grouping in the UI. */
export type ProbabilityBand = 'strong' | 'borderline' | 'weak' | 'unmeasured';

/**
 * `report-pool` means the band is the report's own section 5 bucket.
 * `derived` means it was computed from the report's published thresholds.
 */
export type BandSource = 'report-pool' | 'derived';

export type ProgramType = 'state' | 'foundation' | 'kktc-intl';

/** `null` for state programs, which have no scholarship tier. */
export type ScholarshipTier = 'full' | 'half' | 'quarter' | 'paid' | null;

export interface Program {
  /** Nine-digit ÖSYM programme code. Unique across the dataset. */
  code: string;
  programName: string;
  university: string;
  city: string | null;
  type: ProgramType;
  language: 'tr' | 'en';
  scholarship: ScholarshipTier;
  /** 2025 closing rank; `null` where the programme has no history. */
  closingRank2025: number | null;
  quota2026: number;
  /**
   * Candidate rank minus closing rank. Positive means the candidate sits above
   * the 2025 closing rank, negative means below it. `null` without history.
   */
  rankDistance: number | null;
  band: ProbabilityBand;
  bandSource: BandSource;
  /** The report's finer-grained wording, e.g. "Zayıf ama anlamlı". */
  riskLabel: string;
  /**
   * Annual list payment in TL. `0` means a full scholarship covers it; `null`
   * means no figure applies (state) or none was published. The two must never
   * be conflated in the UI.
   */
  estimatedPayment: number | null;
  /** Cost if the highest confirmed preference discount is obtained. */
  conditionalPreferenceCost: number | null;
  /** Free-text tuition note carried from the faculty group (KKTC / foundation). */
  groupTuitionText: string | null;
  accreditation: string;
  staffSignal: string | null;
  staffCount: number | null;
  /** The report's verbatim assessment of the faculty group as a whole. */
  groupLabel: string | null;
  groupGap: number | null;
  groupGapDirection: 'ahead' | 'behind' | null;
  specialNote: string | null;
  uncertainty: string | null;
  operationalRisk: string | null;
}

export interface Foundation {
  university: string;
  city: string | null;
  listTuition2026: string | null;
  preferenceDiscount: string;
  academicScholarship: string;
  extraBenefits: string;
  /** How far the university's own published sources confirmed the figures. */
  verificationStatus: string;
  accreditation: string;
  staffSignal: string | null;
  staffCount: number | null;
  uncertainty: string | null;
  /** Programme codes belonging to this faculty. */
  codes: string[];
}

export interface ScenarioEntry {
  position: number;
  code: string;
  heading: string;
  data: string | null;
  reasoning: string | null;
  probability: string | null;
  cost: string | null;
  firstYearListCost: string | null;
  conditionalCost: string | null;
}

export interface Scenario {
  id: string;
  title: string;
  intro: string | null;
  entries: ScenarioEntry[];
}

export interface Source {
  /** `1`–`13` for general sources, `V1`–`V32` for foundation-specific ones. */
  id: string;
  label: string;
  url: string;
  /**
   * `false` when the URL shows signs of conversion damage (a line wrap joined
   * two path segments). Those links are shown as plain text, never guessed.
   */
  verified: boolean;
}

export interface ExcludedProgram {
  code: string;
  reason: string;
}

export interface LabelledNote {
  label: string;
  detail: string;
}

export interface FinalCheck {
  order: number;
  text: string;
}

export interface Guidance {
  swapPool: LabelledNote[];
  internationalOptions: LabelledNote[];
  probabilityLabels: LabelledNote[];
  rankHistory: LabelledNote[];
  nearBand: LabelledNote[];
  conditionalCosts: LabelledNote[];
  finalChecks: FinalCheck[];
}

export interface ReportMeta {
  candidateRank: number;
  reportDate: string;
  guideVersion: string;
  preferencePeriod: string;
  counts: {
    programs: number;
    state: number;
    foundation: number;
    international: number;
    stateGroups: number;
    foundationGroups: number;
    internationalGroups: number;
    sources: number;
    unverifiedSources: number;
    excluded: number;
    scenarioEntries: number[];
    bands: Record<ProbabilityBand, number>;
    bandsFromReport: number;
  };
  /** Every ligature repair rule that fired, with its hit count. */
  repairs: { rule: string; count: number }[];
}
